[project]
name = "aidj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "coloredlogs>=15.0.1",
    "mutagen>=1.47.0",
    "pylint>=4.0.4",
    "tqdm>=4.67.1",
]
